<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLGfRvie\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLGfRvie/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLGfRvie.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLGfRvie\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLGfRvie\App_KernelDevDebugContainer([
    'container.build_hash' => 'LGfRvie',
    'container.build_id' => 'f2e21c8b',
    'container.build_time' => 1655104067,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLGfRvie');
